### ISSUE TITLE
http 500 after install extension

### ISSUE THREAD

**Issue by kerim92** [opencorero/opencore#12]
Hi,
Followed steps:
1.fresh opencart 3.0.3 install (last version)
2. go to your OpenCart root folder, open a console and run the following commands step by step
3. git clone https://github.com/opencorero/opencore.git core
4. cd core/
5. composer update screenshot as: 
![image](https://user-images.githubusercontent.com/56412326/81616544-55d7ea80-93ec-11ea-8fcb-c7fab0384f39.png)

6. php artisan key:generate
7. php artisan migrate:install
8. php artisan migrate screenshots as:
![image](https://user-images.githubusercontent.com/56412326/81616661-90da1e00-93ec-11ea-9a6a-a54a32d03006.png)

9. copy OpenCart extension files from core/opencart-module/2.x or 3.x/upload to you OpenCart root folder
10. Optional: in order to enable Developer & Example modules you need to access admin / user / 
![image](https://user-images.githubusercontent.com/56412326/81616872-ff1ee080-93ec-11ea-9601-567c7d302c20.png)
(4 permission given both permission and changes)

11. go to OpenCart admin panel / extensions / extensions / modules, find OpenCore module and install it
 

after install system gone. (http 500)
admin panel not accessible.

when i try to enter website main domain: following errors displayed:
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'notebook_oc.opencore_routes' doesn't exist in /home/notebook/oc.notebookchipset.com/system/library/db/corepdo.php:205 Stack trace: #0 /home/notebook/oc.notebookchipset.com/system/library/db/corepdo.php(205): PDO->prepare('SELECT method, ...') #1 /home/notebook/storage/modification/system/library/db.php(51): DB\corePDO->query('SELECT method, ...') #2 /home/notebook/oc.xxxxx.com/core/support/Opencart/Startup.php(138): DB->query('SELECT method, ...') #3 /home/notebook/oc.xxxxx.com/core/support/Opencart/Startup.php(86): OpenCore\Support\Opencart\Startup->checkOpenCoreRoute() #4 /home/notebook/oc.xxxxx.com/catalog/controller/startup/opencore.php(46): OpenCore\Support\Opencart\Startup->executeIfRouteExists('common/home', NULL, false) #5 /home/notebook/storage/modification/system/engine/action.php(79): ControllerStartupOpencore->before_controller('common/home', NULL) #6 /home/notebook/oc.xxxxx.co in /home/notebook/oc.xxxxx.com/system/library/db/corepdo.php on line 205

phpmyadmin screenshot:
![image](https://user-images.githubusercontent.com/56412326/81615342-190af400-93ea-11ea-9883-11c2f2edd037.png)

screenshot when i try to enter admin panel:
![image](https://user-images.githubusercontent.com/56412326/81615419-3b047680-93ea-11ea-8dbb-3682e8cdf645.png)

all steps replicated two times at live server(vps) can not able to install.
vps: centos 7, cwp panel lastest.
could me my mistake somewhere?

here log in core\storage\laravel 5-12-log.txt
[2020-05-12 01:02:24] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = forge and table_name = opencore_tasks and table_type = 'BASE TABLE')  

ps note:
before click install (+ button) i just backup database. after drop database and install from backup everything works again and extension of course looks not installed.

**Comment by awebdesign** [comment]
Hi,
there's a problem with the documentation.
We are using the master branch for development and the latest version is not completed(indeed is missing the routes table).
Try using our latest release OpenCore v1.2.4, it should work fine without any errors.

Cheers!

**Comment by kerim92** [comment]
Thank you. I will try write if any problem.
