### ISSUE TITLE
 Illuminate\Database\QueryException om php artisan migrate:install

### ISSUE THREAD

**Issue by wayneburlingame** [opencorero/opencore#13]
Hello, on open carts site, when I follow your directions and get to Step: php artisan migrate:install

I get the following error.

Any advice on how to fix?

![image](https://user-images.githubusercontent.com/20672370/81880141-45da1b00-9552-11ea-99cc-448f6d060af3.png)

**Comment by awebdesign** [comment]
Hi,
it seems the SQL driver is missing.
Probably some files were not uploaded / copied.
Delete everything and do it again from scratch using release 1.2.4
https://github.com/opencorero/opencore/releases/tag/1.2.4
