### ISSUE TITLE
upgrading to latest version of Laravel

### ISSUE THREAD

**Issue by eness** [opencorero/opencore#14]
Hey there,

I would like to say thank you for your effort on creating and sharing this project for OpenCart community.

As a Laravel developer, I wish to be able to use latest version of Laravel with this logic. Would it still work if I remove files & folders related to Laravel's original core and replace them with the newest version's of Laravel?

**Comment by awebdesign** [comment]
Hi Eness,
Welcome!

Theoretically yes, it can be done although updating to 5.9 may be easier than updating to 7.
Keep in mind to use the latest release of opencore and not the master branch! Master is used for dev and may contain bugs.
If you do it and it works maybe you will push to changes to opencore in order for other to use it.
Cheers!

**Comment by eness** [comment]
Sounds fine! I'll try to implement latest version. But recently I've noticed that some OpenCart classes such as Session, Config, Response (that all for now) defined in the root namespace conflicts those corresponding defined on top of Laravel's facade system. Is there any genious solution for that? The only way I could think is to rename OpenCart's Session, Config and Response classes name like OpencartSession etc. because it seems they're used at opencart boot to build up the main Registry object (in system/framework.php file)

**Comment by awebdesign** [comment]
most of the OpenCart classes do not use namespaces so it should not be a problem.
In case you have such files in your configuration you will only need to change some Facades names like here:
https://github.com/opencorero/opencore/blob/master/config/app.php
see: Mail changed to IMail.
If you still want to keep the name you can always use the facade like this:
use Illuminate\Support\Facades\Mail;

and Mail will work in your controller.

Cheers!
