### ISSUE TITLE
Argument 2 passed to str_contains() must be of the type string, array given, called in 

### ISSUE THREAD

**Issue by r00t3r5** [opencorero/opencore#16]
after click on modules / modules management / developer or example i get this error why ?
`Argument 2 passed to str_contains() must be of the type string, array given, called in C:\laragon\www\opencart\core\storage\framework\views\9da669a89d7368563acd2dff7f57acb0e079675b.php on line 4 (View: C:\laragon\www\opencart\core\resources\views\admin\core\modules\partials\changelog.blade.php)`

**Comment by awebdesign** [comment]
Are you using the last release OpenCore v1.2.4 ?

**Comment by r00t3r5** [comment]
> Are you using the last release OpenCore v1.2.4 ?

yes, i found a problem if add to composer.json 
"conflict": {
        "symfony/polyfill-php80": "*"
    }
and update everything is okey but if i create a module with command php artisan module:make i get error with routes i dont know how to fix this.

**Comment by awebdesign** [comment]
Maybe that's the problem, that you tried to update it.
It's compatible only with laravel 5.8
